"""Deterministic nearest raster adaptation of pinned arena backgrounds."""
import hashlib
import json
import subprocess
from pathlib import Path
from PIL import Image


def prepare(root, source, repository, revision):
    rows = []
    staged = root / "build/native-presentation/arena-backgrounds"
    staged.mkdir(parents=True, exist_ok=True)
    for png in sorted((source / "images/arenas").glob("*_bg.png")):
        key = png.stem[:-3]
        with Image.open(png) as image:
            source_size = image.size
            if image.width != 320:
                raise ValueError(f"Unsupported arena geometry: {png}: {image.size}")
            runtime_size = (400, image.height * 5 // 4)
            raster = image.convert("RGBA").resize(runtime_size, Image.Resampling.NEAREST)
            adapted = staged / (key + ".png")
            raster.save(adapted)
            crop_width = image.height * 400 / 240
            left = (image.width - crop_width) / 2
            title_box = [left, 0, left + crop_width, image.height]
            title_png = staged / (key + "-title.png")
            image.convert("RGBA").resize((400, 240), Image.Resampling.NEAREST, box=tuple(title_box)).save(title_png)
        target = root / "build/romfs/presentation/arenas" / (key + ".t3x")
        target.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["C:/devkitPro/tools/bin/tex3ds.exe", "-f", "rgba8", "-o", str(target), str(adapted)], check=True, stdout=subprocess.DEVNULL)
        title_target = target.with_name(key + "-title.t3x")
        subprocess.run(["C:/devkitPro/tools/bin/tex3ds.exe", "-f", "rgba8", "-o", str(title_target), str(title_png)], check=True, stdout=subprocess.DEVNULL)
        rows.append({"key": key, "sourcePath": png.relative_to(source).as_posix(),
            "sourceSHA256": hashlib.sha256(png.read_bytes()).hexdigest(),
            "sourceSize": list(source_size), "width": runtime_size[0], "height": runtime_size[1],
            "resampling": "NEAREST", "battleRuntimeScale": 1,
            "titleSourceBox": title_box, "titleRuntimeSize": [400, 240],
            "titleRuntimePath": "romfs:/presentation/arenas/" + key + "-title.t3x",
            "titleStagedSHA256": hashlib.sha256(title_png.read_bytes()).hexdigest(),
            "titleConvertedSHA256": hashlib.sha256(title_target.read_bytes()).hexdigest(),
            "stagedSHA256": hashlib.sha256(adapted.read_bytes()).hexdigest(),
            "runtimePath": "romfs:/presentation/arenas/" + key + ".t3x",
            "convertedSHA256": hashlib.sha256(target.read_bytes()).hexdigest()})
    header = "// Generated by prepare_native_presentation.py from pinned assets.\n#pragma once\n#include <cstdint>\nnamespace Pokerogue3DS {\nstruct ArenaTextureDefinition { const char* key; const char* path; uint16_t width, height; const char* titlePath=nullptr; };\ninline constexpr ArenaTextureDefinition kArenaTextures[] = {\n"
    header += "\n".join('    {"%s", "%s", %d, %d, "%s"},' % (r["key"], r["runtimePath"], r["width"], r["height"], r["titleRuntimePath"]) for r in rows)
    header += "\n};\n}\n"
    (root / "project/generated/include/content/ArenaTextures.hpp").write_bytes(header.encode())
    report = {"schemaVersion": 1, "repository": repository, "revision": revision, "files": rows,
        "runtimeValidation": "NOT_EXECUTED", "limitations": ["Source pixels replicated nonuniformly at 1.25x", "Arena layers still scaled at runtime; title source pixels replicated nonuniformly"]}
    encoded = (json.dumps(report, sort_keys=True, indent=2) + "\n").encode()
    (root / "build/native-presentation/converted-provenance.json").write_bytes(encoded)
    (root / "docs/generated/ARENA_BACKGROUND_REPORT.json").write_bytes(encoded)
    return rows


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    prepare(root, root / "build/native-presentation/source",
        "https://github.com/pagefaultgames/pokerogue-assets",
        "056a1f408f26a3be4fef243f7462cb43608c7928")
